import type { GameCard, ResourceMap } from "../types";
import { emptyResource } from "../types";
import type { GameContext } from "../cardEffects" 

export function createMockContext(overrides: Partial<GameContext> = {}): GameContext {
  const resources: ResourceMap = { ...emptyResource };

  return {
    card: { id: 0, currentSide: 1 } as GameCard,
    zone: "playArea",
    resources,
    cardsForTrigger: [],
    otherEffects: [],
    setResources: (updater) => {
      Object.assign(resources, typeof updater === "function" ? updater(resources) : updater);
    },
    handleGainResources: async () => {},
    handlePayResources: async () => true,
    draw: () => {},
    effectEndTurn: () => {},
    dropToPlayArea: async () => {},
    dropToBlocked: async () => {},
    dropToDeck: async () => {},
    dropToSideDeck: async () => {},
    dropToDiscard: async () => {},
    dropToCampaign: async () => {},
    dropToPermanent: async () => {},
    setDeck: () => {},
    setSideDeck: () => {},
    setPlayArea: () => {},
    setDiscard: () => {},
    setPermanentZone: () => {},
    setCampaignDeck: () => {},
    setTemporaryCardList: () => {},
    setTemporaryCardListImmediate: () => {},
    setBlockedZone: () => {},
    setPurgedCards: () => {},
    setEffectsListImmediate: () => {},
    deleteCardInZone: () => {},
    replaceCardInZone: () => {},
    mill: async () => {},
    openCheckboxPopup: () => {},
    selectResourceChoice: async () => null,
    selectCardsFromZone: async () => [],
    selectCardsFromArray: async () => [],
    discoverCard: async () => false,
    boostProductivity: async () => false,
    registerEndRoundEffect: () => {},
    addCardEffect: () => {},
    fetchCardsInZone: () => [],
    selectCardSides: () => {},
    selectUpgradeCost: () => {},
    selectTextInput: async () => null,
    selectStringChoice: async () => "",
    updateBlocks: () => {},
    getBlockedBy: () => [],
    getCardZone: () => "",
    upgradeCard: async () => true,
    handleCardUpdate: () => {},
    handleEnemyDefeated: async () => {},
    addDiscoverableCard: () => {},
    getCardProduction: () => [],
    hasBeenUsedThisTurn: () => 0,
    markAsUsedThisTurn: () => {},
    t: ((key: string) => key) as any,
    setUpgradeNotEndingTurn: () => {},
    getCardAtIndex: () => undefined,
    filterZone: () => [],
    ...overrides,
  } as GameContext;
}